unik-name/docs.uns.network

docs/uns-usethenetwork/api.md

Update api documentation, add chainmeta:
- /nfts/{id}
- /nfts/{id}/properties
- /wallets/{id}
UPdate api documentation, add nft transactions:
- /nfts/{id}

doc: update apis with chainmeta and transactions datas

---

docs/uns-usethenetwork/cli.md

get-properties command 
Story [#1178](https://spacelephant.tpondemand.com/RestUI/Board.aspx#page=board/4832170605429899055&appConfig=eyJhY2lkIjoiNzkyRUNDNjgwMkEzRDM1RTIwOUE1MkZGNjFCRjQwRjYifQ==&boardPopup=userstory/1178)
https://5d6f86ab020d480007d7004b--developer-uns-network.netlify.com/

doc: add get-properties command

---

docs/uns-usethenetwork/cli.md

set-properties documentation
Story [#1176](https://spacelephant.tpondemand.com/RestUI/Board.aspx#page=board/4832170605429899055&appConfig=eyJhY2lkIjoiNzkyRUNDNjgwMkEzRDM1RTIwOUE1MkZGNjFCRjQwRjYifQ==&searchPopup=userstory/1176)
https://deploy-preview-5--developer-uns-network.netlify.com/

doc: Add set-properties command documentation

---

docs/uns-usethenetwork/cli.md

[#1422](https://spacelephant.tpondemand.com/restui/board.aspx?#page=board/4832170605429899055&appConfig=eyJhY2lkIjoiRjdBMEY0NkNFQzU3NjY3MThBQkQ2RDkwODEzQzU1MzMifQ==&boardPopup=userstory/1383)

doc: update read-wallet command

---

docs/uns-usethenetwork/cli.md

Add unset-properties command documentation
[#1411](https://spacelephant.tpondemand.com/restui/board.aspx?#page=board/4832170605429899055&appConfig=eyJhY2lkIjoiRjdBMEY0NkNFQzU3NjY3MThBQkQ2RDkwODEzQzU1MzMifQ==&boardPopup=userstory/1190)

doc: Add unset-properties command documentation

---

docs/uns-usethenetwork/cli.md
docs/uns-usethenetwork/sdk.md

Close TP #1480 and #1372
- doc for getPropertyValue SDK function: [#1480](https://spacelephant.tpondemand.com/entity/1480-documentation-du-sdk-de-maniere-protegee)
- doc for get-property-value CLI command: [#1372](https://spacelephant.tpondemand.com/entity/1372-documenter-la-commande-get-property-value)

doc: Add get-property-value command and getPropertyValue SDK function

---

docs/uns-usethenetwork/sdk.md

doc: add example for didResolve sdk function

---

docs/uns-use-the-network/cli.md

Merge after [https://github.com/spacelephant/uns-core/pull/50](https://github.com/spacelephant/uns-core/pull/50)

doc: update status command output (removed spaces)

---

docs/uns-use-the-network/cli.md

Add doc for CLI command is-disclosed

doc(CLI): add is-disclosed command doc

---

docs/uns-use-the-network/cli.md

fix: update is-disclosed CLI doc

---

docs/uns-use-the-network/sdk.md

docs: add disclose in SDK

---

docs/uns-use-the-network/cli.md

Add send command documentation [#1477](https://spacelephant.tpondemand.com/entity/1477-documenter-la-commande-cli-greater-send)

doc: add send command documentation

---

docs/uns-use-the-network/cli.md

Allow UNSCLient to use custom chain node url
[#1396](https://spacelephant.tpondemand.com/entity/1396-ron-jutilise-le-flag-node-pour)

doc: add --node flag documentation

---

docs/uns-use-the-network/cli.md

-new awaitConfirmation flag
-Rework help for properties
-delete help commant
-link set/unset-properties

doc(cli): miscellaneous updates

---

docs/uns-use-the-network/cli.md
docs/uns-use-the-network/sdk.md

Rename did-resolve command : [#1516](https://spacelephant.tpondemand.com/entity/1516-ron-evolution-formatage-sortie-did-resolve)

doc: rename did-resolve -> resolve

---

docs/uns-network-key-concepts/cryptography-overview.md
docs/uns-network-player/README.md
docs/uns-use-the-network/api.md
docs/uns-use-the-network/cheatsheet.md
docs/uns-use-the-network/cli.md
docs/uns-use-the-network/sdk.md

doc: remove network flag in commands examples

---

docs/uns-use-the-network/cli.md

doc: update properties:set value short flag

---

docs/uns-use-the-network/cli.md

doc: unik:read command output update with owner balance

---

docs/uns-use-the-network/cli.md

doc: add everlasting command

---

docs/uns-use-the-network/cli.md

- ~Update the `Becoming a Network Player` tutorial with latest CLI~
- Some CLI doc minor edits
___
**Links in the checklist are broken.**

doc: Fix CLI doc
